#services:
#  postgres:
#    image: postgres:15-alpine
#    container_name: my_devip_db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    mem_limit: 128m
#    prometheus:
#      image: prom/prometheus
#      container_name: prometheus
#      volumes:
#        - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      ports:
#        - "9090:9090"
#
#
#  app:
#    image: chichia/devip:latest
#    container_name: my_devip_app
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devip
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: chichia
#      SPRING_PROFILES_ACTIVE: prod
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"
#    ports:
#      - "8080:8080"
#    mem_limit: 128m
#
#
#
#
##  app:
##    image: chichia/devip:latest
##    container_name: my_devip_app
##    environment:
##      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
##      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
##      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
##    depends_on:
##      - postgres
##    ports:
##      - "8080:8080"
##    mem_limit: 128m
#
#volumes:
#  postgres_data:

services:
  postgres:
    image: postgres:15-alpine
    container_name: my_devip_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 128m
    cpus: "0.5"
    deploy:
      replicas: 1

  app:
    image: chichia/devip:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devip
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: chichia
      SPRING_PROFILES_ACTIVE: prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8086"
    mem_limit: 128m
    cpus: "1.0"
    deploy:
      replicas: 3   # Horizontal scaling (number of replicas)
      resources:
        limits:
          cpus: "1.0"
          memory: 128m
        reservations:
          cpus: "0.5"
          memory: 128m
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    mem_limit: 128m

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    mem_limit: 128m

volumes:
  postgres_data:

#  postgres:
#    image: postgres:15-alpine
#    container_name: my_devip_db
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    mem_limit: 128m
#
#  app:
#    image: chichia/devip:latest
#    container_name: my_devip_app
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devip
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: chichia
#      SPRING_PROFILES_ACTIVE: prod
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "10m"
#        max-file: "3"
#    ports:
#      - "8080:8080"
#    mem_limit: 128m


