- name: Set up Monitoring Services
  hosts: monitoring_servers
  tasks:
    - name: Ensure Prometheus is running
      docker_container:
        name: prometheus_terra
        image: prom/prometheus
        state: started
        ports:
          - "9090:9090"
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml

    - name: Ensure Grafana is running
      docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        ports:
          - "3000:3000"
